### PR TITLE
Compatibility with Leaflet 1.0 beta 2 and added some MarkerClusterGroup options

### PR DESCRIPTION
**Pull request by octavm**

### CODE REVIEW

**Comment by mstahv** [comment]
Excellent, thanks!

I didn't do any testing but the stuff looked right to me. Do you need a release for your project? If you need it soon I could try to do short testing tonight and build a release.

**Comment by mstahv** [comment]
Ah, but it is actually not maintained by me, but @willtemperley :-) Will, would you have a look at these changes, pull them into your master branch and build a new version against 1.0 Leaflet soonish?

**Comment by octavm** [comment]
I'm looking forward for a release, that will be great. Thanks!

**Comment by mstahv** [comment]
I merged changes pulled in by @willtemperley with these changes and created a pull request https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5 .

I didn't try at all, but should be pretty easy to test and build a new release now. Thanks in advance!

**Pull request merged**
